package com.drools;

import javafx.scene.control.Button;

global javafx.scene.control.Button whiteButton

rule "Brazowe gowno"
    when
        messageObject: Message()
        gownoObject: Gowno(kolor=="brazowy")
    then
        messageObject.setPrintMessage("Gowno jest brazowe");
        whiteButton.setText("SZTUCZKA");
     end

rule "Czarne gowno"
    when
        messageObject: Message()
        gownoObject: Gowno(kolor=="czarny")
    then
        messageObject.setPrintMessage("Gowno jest czarne");
     end

rule "Biale gowno"
    when
        messageObject: Message()
        gownoObject: Gowno(kolor=="biały")
    then
        messageObject.setPrintMessage("Gowno jest białe");
     end